src/main/java/io/scif/img/ImgOpener.java, src/main/java/io/scif/img/SCIFIOImgPlus.java, src/main/java/io/scif/services/DefaultDatasetIOService.java
Otherwise, the unwrapped Metadata object can be unpopulated in at least some cases. For example, when opening an image from OMERO using the ImageJ-OMERO project's `OMEROFormat`, the following stack trace can occur:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:638) ~[na:1.8.0_11]
at java.util.ArrayList.get(ArrayList.java:414) ~[na:1.8.0_11]
at io.scif.AbstractMetadata.get(AbstractMetadata.java:122) ~[scifio-0.23.0.jar:0.23.0]
at io.scif.services.DefaultDatasetIOService.updateDataset(DefaultDatasetIOService.java:206) ~[scifio-0.23.0.jar:0.23.0]
at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:130) ~[scifio-0.23.0.jar:0.23.0]
at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java …
```
=> Extract ImageMetadata from the properties table

src/main/java/io/scif/formats/DICOMFormat.java
Before this change DICOM attributes with value representation AT
(attribute tag, which means pointers to other attributes using their
tags) are interpreted as strings (and then trimmed) causing meaningless
results.
With this change the value is interpreted as a list of couples [tag
group, tag element] and a user-friendly string is generated; the stirng
is a sequence of 8-characters-long substrings "<tag group><tag element>"
where <tag group> and <tag elements> are 4 characters long each.
Example
Image with value 0x18 0x00 0x63 0x10 (little endian) for the attribute
0028,0009 Frame Incremen Pointer without this change produces the string
"c" and with this change the string "00181063".
=> Correct interpretation of AT DICOM attributes

src/main/java/io/scif/formats/DICOMFormat.java
According to "DICOM PS3.3 2015c - Information Object Definitions", "Pixel Intensity relationship Sign (0028,1041)" is "the sign of the relationship between the Pixel sample values stored in PixelData (7FE0,0010) and the X-Ray beam intensity.". It has nothing to do with setting signed/unisgned to the integer representation of pixel values.
Without this modification if PIXEL_SIGN read after PIXEL_REPRESENTATION the (correct) value of variable signed could be overwritten with a wrong value.
=> Wrong pixel representation sign set

src/main/java/io/scif/formats/dicom/DICOMDictionary.java
HashTable look up is now on key rather than value
HashTable is initialized with the meaningful dimension
=> Correct DICOMDictionary look-up by attribute tag

src/main/java/io/scif/formats/TIFFFormat.java
Instead of writing the micro sign to the IDF ImageDescription tag, write the according unicode tag. When reading a TIFF, convert the unicode tag back.
Seems a little hacky but it's one step in the direction of SCIFIO creating ImageJ1 compatible TIFFs.
=> TIFFFormat: fix unicode <> ascii conversion for mu

src/main/java/io/scif/formats/tiff/TiffSaver.java
The written TIFFs still contained the tag `Software (305) ASCII (2) 16<OME Bio-Formats\0>`.  This PR changes this to read `Software (305) ASCII (2) 7<SCIFIO\0>`.
=> TiffSaver: change TIFF software tag to SCIFIO

src/main/java/io/scif/formats/DICOMFormat.java
When FilePattern.getFiles() creates the string array of file names, it replaces all \ by \. When doing the string comparison with the filenames of Location.list() which does not replace the \ characters, it will fail mainly on Windows.
I just added the same operation of replacing the \ characters so the string comparison will also succeed on Windows machines.
Adding a test would required storing some Dicom files in the repository or creating artificial ones.
=> #329 replace \ by \\ when doing string comparison in DicomFormat.Parser.scanDirectory()

src/main/java/io/scif/Reader.java, src/main/java/io/scif/TypedReader.java
Documenting a pitfall in the readPlane() methods I fell into
=> Add javadocs

src/main/java/io/scif/formats/DICOMFormat.java
When the Photometric Interpretation (0028,0004) has the value
MONOCHROME1, the image is NOT inverted, but an inverted LUT is applied
=> MONOCHROME1 sets an inverted LUT

src/main/java/io/scif/AbstractChecker.java
If an exception is thrown during the `isFormat(RandomAccessInputStream)`
call, the RandomAccessInputStream is not closed, this leads to problems
on Windows, the affected File can only be deleted after the JVM has been
shut down. This commit fixes that.
=> AbstractChecker: always close opened RandomAccessInputStream

src/main/java/io/scif/img/cell/loaders/ByteAccessLoader.java, src/main/java/io/scif/img/cell/loaders/CharAccessLoader.java, src/main/java/io/scif/img/cell/loaders/DoubleAccessLoader.java, src/main/java/io/scif/img/cell/loaders/FloatAccessLoader.java, src/main/java/io/scif/img/cell/loaders/IntAccessLoader.java, src/main/java/io/scif/img/cell/loaders/LongAccessLoader.java, src/main/java/io/scif/img/cell/loaders/ShortAccessLoader.java, src/main/java/io/scif/img/converters/ArrayDataAccessConverter.java
Currently, ArrayDataAccessConverter populates only accesses that are backed by Java arrays. The changes in the pull request extend that to general accesses.
=> Add loaders for general accesses

src/main/java/io/scif/formats/ICSFormat.java
1. Set Ids location during typed parse: other opening `.ics` images written with ics format type 1 fails, as the `.ids` partner file can not be found.
2. The measurement unit was not set during metadata translation, resulting in a loss of information
=> ICSFormat: Metadata fixes

src/main/java/io/scif/img/ImgOpener.java
This option is disabled by default for a good reason, it does not work
with all formats (e.g. gif). We should not set it by default as it makes
it appear as if SCIFIO is unable to handle these affected formats at all.
=> Disable automatic min/max computation in IO.open()

pom.xml, src/main/java/io/scif/formats/ICSFormat.java
This fixes reading of certain ICS/IDS datasets (particularly those written from SVI Huygens) for me when using *File > Import > Image...* in Fiji.
I'd be delighted if this change (or a similar fix) find its way into KNIME Image Processing soon. This would require merging this PR, cutting a new release, updating and releasing `pom-scijava`, and updating [`knip-externals`](https://github.com/knime-ip/knip-externals)  (@ctrueden, @gab1one, @dietzc).
=> Fix ICSFormat to work with unknown axis type

src/main/java/io/scif/formats/MicromanagerFormat.java
For multi-file Micro-Manager formats, the `MicromanagerFormat$Reader` is not initialized properly: the `tiffReader` for reading pixel data is `null`, which results in a `NullPointerException`.
=> MicromanagerFormat: initialize tiffReader

src/main/java/io/scif/formats/MicromanagerFormat.java, src/main/java/io/scif/util/FormatTools.java
`Position.getFile()` would throw an `ArrayIndexOutOfBoundsException` for images that only have one non-planar axis, e.g. only slices. In this case, `FormatTools.rasterToPostion()` will return a one-element array. Subsequent checks for other non-existing dimensions will fail without some additional checking.
=> MicromanagerFormat: fix Position.getFile()

src/test/java/io/scif/io/LocationTest.java
On a related note: on Windows, the "recommended" default setting for git is `core.autocrlf = true`, which causes the `hello-world` file to contain more bytes than expected in the test. A workaround is to change `core.autocrlf` to `input`, but maybe the tests can be adjusted to not rely on checking out a text file on git.
Also, what's the situation about SCIFIO `Locations`? Are they going to be deprecated in favor of those in `scijava-common`?
=> LocationTest: fix order of (expected, actual) in assertions

src/main/java/io/scif/formats/ICSFormat.java
https://github.com/scifio/scifio/commit/686ddcadf74e64830cb5a6557528d3521fdd2da0#r30134302
ICS format can fail to read when not every axis has a unit.
=> ICSFormat: handle extra axes without units

src/main/java/io/scif/formats/BMPFormat.java
This is a port of a fix I did for the new SCIFIO implementation.
The rework done in 0fa9397683caefc227f70f8cffd69406a2086e70 broke the BMPFormat.
Leading to distortions like the following:
=> BMPFormat: fix distortion when reading images, caused by wrong max-size

src/main/java/io/scif/services/DefaultDatasetIOService.java
This removes a redundant `LocationService` parameter that was introduced with commit 856c64a.
=> Remove unused dataHandleService parameter

src/main/java/io/scif/formats/TIFFFormat.java
`setupTiffSaver` should be called after BigTiff detection, otherwise it won't be propagated to the `TiffSaver`
=> TiffFormat: call setupTiffSaver after BigTiff detection

pom.xml, src/main/java/io/scif/img/cell/SCIFIOCellImgFactory.java
This PR updates scifio (SCIFIOCellImg) wrt changes in imglib2-cache 1.0.0-beta-13
(Added to pom-scijava in commit https://github.com/scijava/pom-scijava/commit/22bb44ca55a5d1751b7e1fbb9a797bf5dc82d469)
=> Adopt API changes in imglib2-cache 1.0.0-beta-13

src/main/java/io/scif/img/IO.java, src/test/java/io/scif/AxisGuesserTest.java, src/test/java/io/scif/CheckerTest.java, src/test/java/io/scif/MetadataTest.java, src/test/java/io/scif/TranslatorTest.java, src/test/java/io/scif/filters/FilterTest.java, src/test/java/io/scif/filters/MinMaxFilterTest.java, src/test/java/io/scif/filters/PlaneSeparatorTest.java, src/test/java/io/scif/formats/AbstractFormatTest.java, src/test/java/io/scif/formats/EPSFormatTest.java, src/test/java/io/scif/formats/TestImgFormatTest.java, src/test/java/io/scif/img/ManualReadImg.java, src/test/java/io/scif/img/cell/SCIFIOCellImgTest.java, src/test/java/io/scif/io/location/TestImgLocationResolverTest.java, src/test/java/io/scif/util/FormatToolsTest.java, src/test/java/io/scif/util/ImageHashTest.java, src/test/java/io/scif/writing/APNGWriterTest.java, src/test/java/io/scif/writing/AVIWriterTest.java, src/test/java/io/scif/writing/AbstractSyntheticWriterTest.java, src/test/java/io/scif/writing/EPSWriterTest.java, src/test/java/io/scif/writing/ICSFormatTest.java, src/test/java/io/scif/writing/JPEG2000FormatTest.java, src/test/java/io/scif/writing/JPEGWriterTest.java, src/test/java/io/scif/writing/QTWriterTest.java, src/test/java/io/scif/writing/TiffFormatTest.java
This PR is addressing the breaking API changes from version `0.37.3` (which was the version in `pom-scijava 28.0.0`) and issues with the tests. 
The only breaking changes I could not revert were these:
```
java.method.removed: method void io.scif.img.IO::saveImg(io.scif.Writer, io.scif.img.SCIFIOImgPlus<?>, int): Method was removed.
java.method.removed: method void io.scif.img.IO::saveImg(io.scif.Writer, net.imglib2.img.Img<?>): Method was removed.
```
The `ImgSaver` does not have methods to save by passing a `Writer`, so I'm not sure how to fix this.
I have not tested it with the melting pot yet.
I was not able to run the tests locally, I ran into `java.lang.OutOfMemoryError: Java heap space` errors all the time, that's why I added a commit to dispose all contexts created in the tests. I …
=> IO API: fix breaking changes compared to 0.37.x

src/main/java/io/scif/img/cell/loaders/AbstractArrayLoader.java
This is an attempt to fix issues like #399. The issue is also reproducible with many SCIFIO JUnit tests when forcing the `ImgOpener` to use the `SCIFIOCellImgFactory` and this PR seems to solve it.
=> AbstractArrayLoader: fix ImageMetadata access

src/main/java/io/scif/img/cell/SCIFIOCellImg.java, src/main/java/io/scif/img/cell/SCIFIOCellImgFactory.java
An attempt to fix #424 by keeping a reference to the `IoSync` object and shutting it down on dispose. It was the simplest strategy I could come up with, but it changes the signature of `SCIFIOCellImg`.
=> SCIFIOCellImg: Fix memory leak

src/main/java/io/scif/AbstractWriter.java, src/main/java/io/scif/config/SCIFIOConfig.java, src/test/java/io/scif/writing/APNGWriterTest.java, src/test/java/io/scif/writing/AVIWriterTest.java, src/test/java/io/scif/writing/AbstractSyntheticWriterTest.java, src/test/java/io/scif/writing/EPSWriterTest.java, src/test/java/io/scif/writing/ICSFormatTest.java, src/test/java/io/scif/writing/JPEG2000FormatTest.java, src/test/java/io/scif/writing/JPEGWriterTest.java, src/test/java/io/scif/writing/QTWriterTest.java, src/test/java/io/scif/writing/TiffFormatTest.java
Updates the default behavior for SCIFIO writers to fail when attempting to overwrite, with exposed configuration options for forcing an overwrite.
Adds tests for each format's current overwrite behavior. Note that QT, APNG and ICS do not produce valid output when overwriting at this time.
=> Improve overwriting behavior

src/main/java/io/scif/img/IO.java, src/main/java/io/scif/img/ImgSaver.java
- partially restoring backwards compatibility to SCIFIO version `0.37.3` for `ImgSaver` and `ImgOpener`
- together with https://github.com/scifio/scifio/pull/427, this likely fixes the issues mentioned in [this forum post](https://forum.image.sc/t/33385/7)
For testing, I added this to the POM:
```
<build>
<plugins>
<plugin>
<groupId>org.revapi</groupId>
<artifactId>revapi-maven-plugin</artifactId>
<version>0.11.4</version>
<dependencies>
<dependency>
<groupId>org.revapi</groupId>
<artifactId>revapi-java</artifactId>
<version>0.20.2</version>
</dependency>
</dependencies>
<executions>
<execution>
<id>check</id>
<goals><goal>check</goal></goals>
</execution>
</executions>
<configuration>
<oldVersion>0.37.3</oldVersion>
<failSeverity>breaking</failSeverity>
<analysisConfiguration>
{ …
```
=> ImgSaver, ImgOpener: restore backwards compatibility to version 0.37.3

src/main/java/io/scif/services/DatasetIOService.java, src/main/java/io/scif/services/DefaultDatasetIOService.java
This re-adds the previously available `save(Dataset, String, SCIFIOConfig)` method.
=> DatasetIOService: re-add save method

pom.xml
See https://github.com/scijava/scijava-common/issues/406.
With `scijava-common-2.84.0`, the generic typing of `AbstractIOPlugin` has changed from `String` to `Location`. While the `String`-based methods were kept for compatibility, we have to re-compile SCIFIO with a newer dependency to restore binary compatibility.
=> Pin to scijava-common 2.85.0

src/main/java/io/scif/convert/FileToDatasetConverter.java, src/main/java/io/scif/convert/StringToDatasetConverter.java, src/test/java/io/scif/convert/FileToDatasetConverterTest.java, src/test/java/io/scif/convert/StringToDatasetConverterTest.java
Closes #434.
This pull request changes `FileToDatasetConverter` and `StringToDatasetConverter` to only accept conversion requests when the input file can actually be opened by `DatasetIOService`.
Most importantly, we don't claim supporting a `String -> Dataset` conversion solely based on the types, as this could interfere with a (yet-to-be-created) `StringToDatasetConverter` in `imagej-legacy` (as well as [the current one in `ilastik4ij`](https://github.com/ilastik/ilastik4ij/blob/95473a567c0f03e24b076e964484d4f043596693/src/main/java/org/ilastik/ilastik4ij/util/StringToDatasetConverter.java)) that would look for opened images named as the input `String` (see also [`StringToImagePlusConverter`](https://github.com/imagej/imagej-legacy/blob/5d66b5314f75810fe1f8ff8db1323b9941c3d2ee/src/main/j …
=> Make StringToDatasetConverter more conservative

src/main/java/io/scif/formats/TIFFFormat.java, src/test/java/io/scif/writing/TiffFormatTest.java
This pull request adds support for the Deflate compression (`CompressionType.ZLIB`) to the `TIFFFormat` that was previously ignoring that option when it was set via `SCIFIOConfig.writerSetCompression()`.
While at it, I had to fix the way the compression is configured in the `TiffFormatTest`, where `CompressionType.toString()` was used.
For all codecs except LZW, the toString() method returns something different from getCompression():
* `ZLIB` <=> `zlib`
* `J2K` <=> `JPEG-2000`
* `J2K_LOSSY` <=> `JPEG-2000 Lossy`
* `LZW` <=> `LZW`
Hence these tests weren't actually testing the correct compressions, but just the fallback, `UNCOMPRESSED`.
Fixing this revealed that the `J2K` and `J2K_LOSSY` compressions currently have issues, therefore let's temporarily ignore their tests, until someone has …
=> Add support for Deflate (zlib) compression when writing TIFF

src/main/java/io/scif/convert/FileToDatasetConverter.java, src/test/java/io/scif/convert/FileToDatasetConverterTest.java, src/test/java/io/scif/convert/StringToDatasetConverterTest.java
It turns out that `io.canOpen` actually returns **true** for a file like `blobs.gif` even if it doesn't exist on the given path (see https://github.com/scifio/scifio/issues/434#issuecomment-1057944811). `FileToDatasetConverter` should really only be accepting requests where the file exists (or the name ends with `.fake` for the special case of the fake file format).
The tests are adjusted to be testing for unsupported formats as well as non-existing but theoretically supported files.
Closes #434.
Should also fix https://github.com/scijava/scijava-common/issues/442.
=> Fix FileToDatasetConverter picking up non-existing files

src/main/java/io/scif/services/DefaultFormatService.java
closes #481 
1. Currently, when you try to export an image as an unsupported extension it will throw an error: 
`No compatible output format found for extension`
This pull request adds additional information to that error as a list of all of the compatible formats they could choose.
2. This pull request also changes [addComponents(final Format format)](https://github.com/scifio/scifio/blob/compatible-output-formats/src/main/java/io/scif/services/DefaultFormatService.java#L197) to not include instances of `DefaultWriter.class` - for which there are no compatible output formats - in `writerMap`.
=> Show compatible output formats during export error message
